# Pipeline configuration

# --- Input
inputdir: "example_data"
genome_extension: "{genome}.fa" 
dbdir: "databases" 
metadata: "data/metadata.csv" #only necessary if feature selection == True

# --- Output directory
outdir: "results" 
outdir_anno: "results/Annotation" 
logdir: "logs"

# --- Evalues:
cog_evalue: "1e-5"
pfam_evalue: "1e-5"

# --- Run Feature Selection (True or False)
FS: False
# Note: To run Feature Selection add metadata.csv to inputdir folder!
